### ISSUE TITLE
ImportError(No module named applications.places.modules.StringIO)

### ISSUE THREAD

**Issue by Mustafalb** [richardpenman/wswp_places#9]
When I tried to install the web page and run it in web2py.
in the latter screenshot is where I placed the installed webpage
![Screenshot 2023-02-19 122818](https://user-images.githubusercontent.com/32560780/219939922-48e7e775-737c-4840-bd8c-46c57045436b.png)

**Comment by ahmadore** [comment]
I was able to fix this error.

Go to applications>places>modules>common.py

Replace line 6 - 9 which is currently

```
try:
    import cStringIO as StringIO
except ImportError:
    import StringIO
```

With

```
try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
```
and line 376 from `fp = StringIO.StringIO(text)` to `fp = StringIO(text)`
